spring:
  datasource:
    url: jdbc:mysql://localhost:3306/bms_schema?setUnicode=true&characterEncoding=utf8
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
server:
  port: 8080
mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml # mybatis配置文件所在路径
  type-aliases-package: com.example.bookmanagementsystem.bean # 所有Entity别名类所在包
  mapper-locations: classpath:mybatis/mappers/**/*.xml # mapper映射文件
